"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { CalendarOff, Clock3, LoaderCircle, Plus, RefreshCw, Trash2 } from "lucide-react";

const times=["08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00"];
const today=()=>{const value=new Date();return new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,10);};
type Block={id:string;block_date:string;block_time:string|null;reason:string};

export default function AvailabilityManager(){
  const [blocks,setBlocks]=useState<Block[]>([]); const [date,setDate]=useState(today); const [time,setTime]=useState("all"); const [reason,setReason]=useState("");
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  const load=useCallback(async()=>{setLoading(true);const response=await fetch("/api/barbeiro/disponibilidade",{cache:"no-store"});const data=await response.json();if(response.ok)setBlocks(data.blocks);else setMessage(data.error??"Não foi possível carregar.");setLoading(false);},[]);
  useEffect(()=>{load();},[load]);
  async function create(event:FormEvent){event.preventDefault();setSaving(true);setMessage("");const response=await fetch("/api/barbeiro/disponibilidade",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,time:time==="all"?null:time,reason})});const data=await response.json();if(response.ok){setReason("");setMessage("Período bloqueado com sucesso.");await load();}else setMessage(data.error??"Não foi possível bloquear.");setSaving(false);}
  async function remove(id:string){setMessage("");const response=await fetch(`/api/barbeiro/disponibilidade?id=${encodeURIComponent(id)}`,{method:"DELETE"});const data=await response.json();if(response.ok)setBlocks(current=>current.filter(item=>item.id!==id));else setMessage(data.error??"Não foi possível remover.");}
  return <><section className="barber-heading availability-heading"><div><p className="barber-kicker">CONTROLE DE AGENDA</p><h1>Disponibilidade.</h1><p>Bloqueie folgas, compromissos ou horários que não devem aparecer para clientes.</p></div><CalendarOff/></section><section className="availability-layout"><form className="availability-form" onSubmit={create}><div><p className="barber-kicker">NOVO BLOQUEIO</p><h2>Reservar período.</h2></div><label>Data<input type="date" min={today()} value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Período<select value={time} onChange={e=>setTime(e.target.value)}><option value="all">Dia inteiro</option>{times.map(item=><option key={item} value={item}>{item}</option>)}</select></label><label>Motivo <small>opcional</small><input maxLength={120} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: folga ou compromisso"/></label><button className="barber-primary" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Plus/>}{saving?"Salvando…":"Bloquear na agenda"}</button></form><section className="availability-list"><div className="availability-list-head"><div><p className="barber-kicker">PRÓXIMOS BLOQUEIOS</p><h2>Períodos indisponíveis.</h2></div><button onClick={load} aria-label="Atualizar bloqueios"><RefreshCw className={loading?"spin":""}/></button></div>{message&&<p className="availability-message">{message}</p>}{loading?<div className="barber-empty"><LoaderCircle className="spin"/></div>:blocks.length===0?<div className="barber-empty"><CalendarOff/><h3>Agenda totalmente disponível.</h3><p>Os bloqueios criados aparecerão aqui.</p></div>:<div className="availability-items">{blocks.map(block=><article key={block.id}><span className="availability-date"><strong>{new Date(`${block.block_date}T12:00:00`).toLocaleDateString("pt-BR",{day:"2-digit"})}</strong><small>{new Date(`${block.block_date}T12:00:00`).toLocaleDateString("pt-BR",{month:"short"}).replace(".","")}</small></span><span><strong>{block.reason}</strong><small><Clock3/>{block.block_time?block.block_time.slice(0,5):"Dia inteiro"}</small></span><button onClick={()=>remove(block.id)} aria-label={`Remover bloqueio de ${block.reason}`}><Trash2/></button></article>)}</div>}</section></section></>;
}
