import { NextRequest, NextResponse } from "next/server";
import { requireBarber } from "@/lib/barber-auth";

const times=new Set(["08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00"]);
function config(){const url=process.env.SUPABASE_URL;const key=process.env.SUPABASE_PUBLISHABLE_KEY;return url&&key?{url,key}:null;}

export async function GET(){const session=await requireBarber().catch(()=>null);if(!session)return NextResponse.json({error:"Não autorizado."},{status:401});const supabase=config();if(!supabase)return NextResponse.json({error:"Banco não configurado."},{status:503});const today=new Date().toISOString().slice(0,10);const query=new URLSearchParams({select:"id,block_date,block_time,reason,created_at",block_date:`gte.${today}`,order:"block_date.asc,block_time.asc"});const response=await fetch(`${supabase.url}/rest/v1/availability_blocks?${query}`,{headers:{apikey:supabase.key,Authorization:`Bearer ${session.accessToken}`},cache:"no-store"});if(!response.ok)return NextResponse.json({error:"Não foi possível carregar os bloqueios."},{status:502});return NextResponse.json({blocks:await response.json()});}

export async function POST(request:NextRequest){const session=await requireBarber().catch(()=>null);if(!session)return NextResponse.json({error:"Não autorizado."},{status:401});const body=(await request.json().catch(()=>null)) as null|{date?:string;time?:string|null;reason?:string};if(!body||!/^\d{4}-\d{2}-\d{2}$/.test(body.date??"")||(body.time!==null&&body.time!==undefined&&!times.has(body.time))||(body.reason?.length??0)>120)return NextResponse.json({error:"Bloqueio inválido."},{status:400});const supabase=config();if(!supabase)return NextResponse.json({error:"Banco não configurado."},{status:503});const response=await fetch(`${supabase.url}/rest/v1/availability_blocks`,{method:"POST",headers:{apikey:supabase.key,Authorization:`Bearer ${session.accessToken}`,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({block_date:body.date,block_time:body.time||null,reason:body.reason?.trim()||"Indisponível"}),cache:"no-store"});if(!response.ok){const message=await response.text();if(message.includes("duplicate key"))return NextResponse.json({error:"Este período já está bloqueado."},{status:409});if(message.includes("confirmed_booking_conflict"))return NextResponse.json({error:"Já existe cliente confirmado neste período. Altere o agendamento antes de bloquear."},{status:409});return NextResponse.json({error:"Não foi possível salvar o bloqueio."},{status:502});}return NextResponse.json({block:(await response.json())[0]},{status:201});}

export async function DELETE(request:NextRequest){const session=await requireBarber().catch(()=>null);if(!session)return NextResponse.json({error:"Não autorizado."},{status:401});const id=request.nextUrl.searchParams.get("id")??"";if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id))return NextResponse.json({error:"Bloqueio inválido."},{status:400});const supabase=config();if(!supabase)return NextResponse.json({error:"Banco não configurado."},{status:503});const response=await fetch(`${supabase.url}/rest/v1/availability_blocks?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:{apikey:supabase.key,Authorization:`Bearer ${session.accessToken}`},cache:"no-store"});if(!response.ok)return NextResponse.json({error:"Não foi possível remover o bloqueio."},{status:502});return NextResponse.json({success:true});}
